// About Flunkey: a candid founder story, technical context, and the visual work behind the product.
import { Link } from "wouter";
import { ArrowLeft, ArrowUpRight, Code2, ExternalLink, FileText, Home, KeyRound, Mail, Play, Sparkles, Timer, Wrench } from "lucide-react";

import logo from "@assets/flunkey_logo.webp";
import posterAnimation from "@assets/poster_animation.gif";
import rohanPortrait from "@assets/rohan_halftone_edit.webp";

function AboutHeader() {
  return <header className="about-header"><Link className="about-mark" href="/" aria-label="Flunkey home"><img src={logo} alt="" /></Link><nav className="about-nav" aria-label="About navigation"><Link href="/docs" aria-label="Documentation" title="Documentation"><FileText size={16} /></Link><Link href="/" aria-label="Flunkey tour" title="Tour"><Home size={16} /></Link></nav></header>;
}

export default function About() {
  return <div className="about-shell"><AboutHeader /><main className="about-main"><section className="about-hero"><div><span className="about-kicker">Flunkey / About</span><h1>Rohan Sharvesh</h1><div className="about-present">presents flunkey</div><div className="about-hero-meta"><span><Timer size={14} /> 5–6 months in the making</span><span><Wrench size={14} /> Built for Windows</span></div></div><div className="about-hero-portrait"><img src={rohanPortrait} alt="Rohan Sharvesh, creator of Flunkey" /><span>creator · flunkey</span></div></section>
<section className="about-story"><div className="about-section-index">01</div><div className="about-story-copy"><span className="about-kicker">The beginning</span><h2>I wanted a question<br /><em>to have somewhere to go.</em></h2><p>I’m a 17-year-old developer, and I built Flunkey first for my own use case. I wanted to press a hotkey, ask a question, and have an LLM give me a response right there — no context switching, no extra tab, no interruption.</p><p>I couldn’t find another app that worked that way for me, so I built one. It took five to six months of experimenting, designing, debugging, and slowly turning a personal shortcut into something that actually works.</p><div className="about-quote"><Sparkles size={18} /><span>“The most important use case is often the one that makes your own day easier.”</span></div></div></section>
<section className="about-build"><div className="about-section-index">02</div><div><span className="about-kicker">How it is built</span><h2>Small, fast, and<br /><em>yours to configure.</em></h2><div className="about-build-grid"><article><div className="about-card-icon"><Code2 size={18} /></div><h3>Rust + Tauri</h3><p>Flunkey uses a Rust-based Tauri framework because it is lighter and faster than heavier desktop stacks. The goal is a Windows app that can run comfortably on more computers.</p></article><article><div className="about-card-icon"><KeyRound size={18} /></div><h3>Bring your own key</h3><p>Flunkey follows a BYOK model using the Groq API. You plug in your own Groq API key, so the model connection belongs to you and the setup stays transparent.</p></article><article><div className="about-card-icon"><Wrench size={18} /></div><h3>Designed, not assembled</h3><p>The logo, posters, and visual language were designed by the same person building the product. The rough edges are part of a real project becoming more useful over time.</p></article></div><a className="about-mvp-link" href="https://github.com/FlunkeyManager/flunkey-app" target="_blank" rel="noreferrer"><span><Code2 size={16} /> MVP repository on GitHub</span><ArrowUpRight size={15} /></a></div></section>
<section className="about-name"><div className="about-section-index">03</div><div className="about-name-card"><div><span className="about-kicker">Why “Flunkey”?</span><h2>A catchy name for<br /><em>small useful tasks.</em></h2><p>“Flunkey” means someone who performs small, unimportant tasks — quite an appropriate name for a tool that helps with the little things between bigger pieces of work.</p><a href="https://www.merriam-webster.com/dictionary/flunkey" target="_blank" rel="noreferrer">Read the dictionary reference <ExternalLink size={14} /></a></div><div className="about-name-glyph">f<span>small task<br />big momentum</span></div></div></section>
<section className="about-poster"><div className="about-section-index">04</div><div><span className="about-kicker">Made along the way</span><h2>A little of the<br /><em>visual experiment.</em></h2><p>The posters and motion pieces are part of the same process: making the idea easier to feel before it is easier to explain.</p><figure><img src={posterAnimation} alt="Animated Flunkey poster artwork" /><figcaption><Play size={13} /> Poster animation · designed for Flunkey</figcaption></figure></div></section>
<section className="about-contact"><div><span className="about-kicker">Keep in touch</span><h2>Questions, ideas,<br /><em>or just hello.</em></h2><p>Flunkey is still growing. If you have a thoughtful question or want to share how you would use it, write directly.</p></div><div className="about-contact-links"><a href="mailto:rohansharvesh@gmail.com"><Mail size={16} /> rohansharvesh@gmail.com <ArrowUpRight size={14} /></a><a href="mailto:flunkeymanager@gmail.com"><Mail size={16} /> flunkeymanager@gmail.com <ArrowUpRight size={14} /></a><a href="https://x.com/Flunkeymanager" target="_blank" rel="noreferrer"><ExternalLink size={16} /> X / Flunkeymanager <ArrowUpRight size={14} /></a><a href="https://www.instagram.com/flunkeymanager/" target="_blank" rel="noreferrer"><ExternalLink size={16} /> Instagram / Flunkeymanager <ArrowUpRight size={14} /></a></div></section>
</main><footer className="about-footer"><span>Flunkey · voice-first productivity for Windows</span><span>Built with curiosity.</span></footer></div>;
}
