// Quiet Intelligence docs: video-first product education, illustrative flow diagrams, and practical controls.
import { Link } from "wouter";
import { ArrowLeft, ArrowUpRight, Brain, Check, ChevronRight, FileText, Home, Info, Keyboard, LockKeyhole, Mic, Network, PenLine, Play, Search, Sparkles, Wand2 } from "lucide-react";

import logo from "@assets/flunkey_logo.webp";

const markImage = logo;
const videoId = "rWqHoINYBVw";

const sections = [
  ["watch", "Watch the walkthrough"], ["overview", "What Flunkey is"], ["transcription", "Voice-to-text"], ["assistant", "Voice-to-AI assistant"], ["rewrite", "Rewrite and refine"], ["memory", "Personal memory"], ["mcp", "Connecting tools"], ["privacy", "Privacy & control"],
];

function DocsHeader() {
  return <header className="docs-header"><Link className="brand" href="/"><img src={markImage} alt="" /><span>flunkey</span></Link><div className="docs-header-right"><Link className="docs-icon-link" href="/about" aria-label="About Flunkey" title="About Flunkey"><Info size={16} /></Link><Link className="docs-icon-link" href="/" aria-label="Flunkey tour" title="Tour"><Home size={16} /></Link></div></header>;
}

function FlowDiagram() {
  return <div className="docs-flow-diagram" aria-label="Flunkey flow: speak, understand, review, confirm"><div className="flow-node flow-speak"><Mic size={18} /><span>Speak</span><small>your rough thought</small></div><div className="flow-line"><i /><ArrowRightSmall /></div><div className="flow-node flow-understand"><Brain size={18} /><span>Understand</span><small>context + intent</small></div><div className="flow-line"><i /><ArrowRightSmall /></div><div className="flow-node flow-review"><PenLine size={18} /><span>Review</span><small>edit the shape</small></div><div className="flow-line"><i /><ArrowRightSmall /></div><div className="flow-node flow-confirm"><Check size={18} /><span>Confirm</span><small>you stay in charge</small></div></div>;
}

function ArrowRightSmall() { return <span className="flow-arrow">→</span>; }

export default function Docs() {
  return <div className="docs-shell"><DocsHeader /><div className="docs-layout"><aside className="docs-rail"><Link className="back-link" href="/"><ArrowLeft size={15} /> Back to Flunkey</Link><div className="docs-rail-title">On this page</div>{sections.map(([id, label]) => <a key={id} href={`#${id}`}><span>{label}</span><ChevronRight size={14} /></a>)}<div className="docs-rail-note"><LockKeyhole size={15} /><span>Local-first by design.<br />Your memory stays yours.</span></div></aside><main className="docs-main"><div className="docs-eyebrow">Flunkey / Documentation</div><h1>See the whole idea<br /><em>in motion.</em></h1><p className="docs-lede">Start with the walkthrough, then explore how Flunkey turns speech into text, useful actions, and remembered context without pulling you out of the app you already use.</p><div className="docs-updated">A visual guide to the product, its capabilities, and the controls behind it.</div>
<section id="watch" className="docs-video-section"><div className="docs-video-heading"><div><span className="docs-section-kicker">01 / watch first</span><h2>From a thought<br /><em>to something useful.</em></h2></div><span className="video-runtime"><Play size={13} /> Flunkey walkthrough</span></div><div className="docs-video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${videoId}?autoplay=1&mute=1&controls=1&playsinline=1&rel=0&modestbranding=1`} title="Flunkey product walkthrough" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /><div className="video-caption"><span><span className="video-live-dot" /> Autoplay is muted so the guide can start reliably</span><a href={`https://www.youtube.com/watch?v=${videoId}`} target="_blank" rel="noreferrer">Open on YouTube <ArrowUpRight size={13} /></a></div></div></section>
<div className="docs-hotkey-strip"><kbd>⌥ space</kbd><span>say a thought</span><span className="hotkey-arrow">→</span><kbd>⌥ enter</kbd><strong>make it useful</strong><span className="hotkey-arrow">→</span><span>review · edit · confirm</span></div>
<section id="overview" className="doc-section docs-overview"><div className="doc-number">02</div><div><span className="docs-section-kicker">The simple model</span><h2>Flunkey sits<br /><em>between thinking and doing.</em></h2><p>Flunkey is a voice-first productivity layer for Windows. It is not just dictation and it is not a chatbot you have to leave your work to visit. It gives your thoughts a direct route to the place where they can become useful.</p><FlowDiagram /><div className="doc-callout"><strong>Nothing happens behind your back.</strong><span>Flunkey prepares the text or action. You decide what gets kept, sent, or changed.</span></div></div></section>
<section id="transcription" className="doc-section"><div className="doc-number">03</div><div><span className="docs-section-kicker">Voice capture</span><h2>Voice-to-text<br /><em>at the cursor.</em></h2><p>Press the transcription hotkey and speak naturally. Flunkey removes filler words, fixes punctuation and capitalization, and formats the stream into readable text directly inside the app you are already using.</p><div className="docs-explainer-card transcript-card"><div className="explainer-top"><span><Mic size={15} /> listening</span><kbd>⌥ space</kbd></div><div className="explainer-wave">{[1,2,3,4,5,6,7,8,9,10].map(n => <i key={n} style={{height:`${12 + ((n * 11) % 28)}px`}} />)}</div><div className="explainer-result"><Check size={15} /><span>Clean text appears where your cursor is already waiting.</span></div></div><div className="doc-check-list"><div><Check size={15} /> Directly at the cursor in any app</div><div><Check size={15} /> Custom dictionary for names and jargon</div><div><Check size={15} /> Multilingual speech and code-switching</div><div><Check size={15} /> In-dictation commands like “new paragraph”</div></div></div></section>
<section id="assistant" className="doc-section docs-dark-section"><div className="doc-number">04</div><div><span className="docs-section-kicker">Interpretation</span><h2>Voice-to-AI<br /><em>assistant.</em></h2><p>Use the second hotkey for requests that need interpretation or more than one step. Flunkey can organize what you said into a task, note, reminder, draft, or answer while keeping the result visible and editable.</p><div className="docs-intent-grid"><div><Sparkles size={17} /><strong>Capture</strong><span>“Turn this into a structured note.”</span></div><div><Keyboard size={17} /><strong>Plan</strong><span>“Remind me next Tuesday.”</span></div><div><FileText size={17} /><strong>Communicate</strong><span>“Draft a concise email.”</span></div><div><Search size={17} /><strong>Understand</strong><span>“What did I say about Q3?”</span></div></div></div></section>
<section id="rewrite" className="doc-section"><div className="doc-number">05</div><div><span className="docs-section-kicker">Editability</span><h2>Rewrite the shape<br /><em>without losing yourself.</em></h2><p>Flunkey can make a rough message clearer, shorter, warmer, or more direct. The original remains visible so you can compare, edit, and choose the version that sounds right.</p><div className="docs-rewrite-card"><div><span>before</span><p>“Could we maybe find a time next week to talk about this?”</p></div><div className="rewrite-divider">↘</div><div className="rewrite-after"><span>after · clearer</span><p>“Could we schedule time next week to discuss this?”</p></div><footer><PenLine size={13} /> Edit before you use it <button>Keep this version <Check size={12} /></button></footer></div></div></section>
<section id="memory" className="doc-section docs-memory-section"><div className="doc-number">06</div><div><span className="docs-section-kicker">Personal context</span><h2>The brain: personal<br /><em>memory.</em></h2><p>Every capture can become part of a running personal memory. Flunkey processes notes, to-dos, reminders, questions, and recurring topics so you can ask about your own recent work in plain language.</p><div className="docs-memory-visual"><div className="memory-orbit-card"><Brain size={18} /><strong>What did I say about Q3?</strong><span>3 relevant moments · last Tuesday</span></div><div className="memory-orbit-line line-a" /><div className="memory-orbit-line line-b" /><div className="memory-orbit-dot dot-a" /><div className="memory-orbit-dot dot-b" /><div className="memory-orbit-dot dot-c" /></div><div className="doc-callout orange"><strong>You stay in control.</strong><span>View, correct, exclude, export, or delete stored memories at any time.</span></div></div></section>
<section id="mcp" className="doc-section"><div className="doc-number">07</div><div><span className="docs-section-kicker">Connected capability</span><h2>Your tools become<br /><em>part of the sentence.</em></h2><p>Flunkey can connect to Gmail, Google Calendar, Slack, Discord, Notion, and other MCP-compatible tools. Connections give Flunkey capabilities; they never remove your final approval step.</p><div className="mcp-steps"><div><span>1</span><p><strong>Connect once</strong>Authorize the service through its normal permission flow.</p></div><div><span>2</span><p><strong>Ask naturally</strong>“Set up a call with Priya next week” can check real calendar conflicts.</p></div><div><span>3</span><p><strong>Review and confirm</strong>Edit the draft, then approve the write action yourself.</p></div></div><div className="docs-capability-strip"><Network size={17} /><span>One sentence</span><b>→</b><span>multiple prepared actions</span><Check size={17} /></div></div></section>
<section id="privacy" className="doc-section docs-privacy-section"><div className="doc-number">08</div><div><span className="docs-section-kicker">Trust by design</span><h2>Useful should never<br /><em>mean out of your hands.</em></h2><p>Flunkey is designed local-first, with optional cloud sync for people who want it. Sensitive topics can be excluded from memory, and the controls are visible instead of hidden in fine print.</p><div className="privacy-table"><div><LockKeyhole size={16} /><span>Storage</span><strong>Local-first, optional sync</strong></div><div><EyeMini /><span>Visibility</span><strong>Inspect your stored memory</strong></div><div><ArrowUpRight size={16} /><span>Portability</span><strong>Export everything</strong></div><div><WandMini /><span>Deletion</span><strong>Delete individual or all memories</strong></div></div><div className="docs-privacy-links"><Link href="/privacy">Read the full Privacy Policy <ArrowUpRight size={13} /></Link><Link href="/terms">Terms of Service <ArrowUpRight size={13} /></Link></div></div></section>
<div className="docs-footer-cta"><div><span className="section-kicker">Keep exploring</span><h2>Return to the tour<br /><em>when you’re ready.</em></h2></div></div></main></div><footer className="docs-footer"><Link className="brand" href="/"><img src={markImage} alt="" /><span>flunkey</span></Link><div className="docs-legal-wrap"><span>Voice-first productivity for Windows.</span><span className="docs-legal-links"><Link href="/terms">Terms of Service</Link><i /><Link href="/privacy">Privacy Policy</Link></span></div></footer></div>;
}

function EyeMini() { return <span className="mini-symbol">◉</span>; }
function WandMini() { return <span className="mini-symbol">✦</span>; }
